name: Release

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup msvc amd64_x86
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86
      - name: Build amd64_x86
        run: |
          msbuild

      - name: Setup msvc amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: Build amd64
        run: |
          msbuild